export const recipes = [
  { name: 'Conserva de cenoura', difficulty: 'Fácil', kind: 'Salgada', image: 'cenoura.webp' },
  { name: 'Beterraba em conserva', difficulty: 'Fácil', kind: 'Salgada', image: 'beterraba.webp' },
  { name: 'Abobrinha agridoce', difficulty: 'Fácil', kind: 'Salgada', image: 'abobrinha.webp' },
  { name: 'Relish de pimentão e cebola', difficulty: 'Fácil', kind: 'Salgada', image: 'relish-pimentao.webp' },
  { name: 'Picles de pepino com endro', difficulty: 'Intermediária', kind: 'Salgada', image: 'pepino.webp' },
  { name: 'Quiabo com endro', difficulty: 'Intermediária', kind: 'Salgada', image: 'quiabo.webp' },
  { name: 'Conserva de vegetais mistos', difficulty: 'Intermediária', kind: 'Salgada', image: 'vegetais.webp' },
  { name: 'Relish de pepino com endro', difficulty: 'Intermediária', kind: 'Salgada', image: 'relish-pepino.webp' },
  { name: 'Pimentões marinados', difficulty: 'Avançada', kind: 'Salgada', image: 'pimentoes.webp' },
  { name: 'Conserva de casca de melancia', difficulty: 'Avançada', kind: 'Salgada', image: 'melancia.webp' },
  { name: 'Relish de pimentas', difficulty: 'Avançada', kind: 'Salgada', image: 'relish-pimentas.webp' },
  { name: 'Geleia de morango', difficulty: 'Fácil', kind: 'Doce', image: 'morango.webp' },
  { name: 'Geleia de pêssego', difficulty: 'Intermediária', kind: 'Doce', image: 'pessego.webp' },
  { name: 'Geleia de uva Concord', difficulty: 'Intermediária', kind: 'Doce', image: 'uva.webp' },
  { name: 'Doce de pêssego com abacaxi', difficulty: 'Intermediária', kind: 'Doce', image: 'pessego-abacaxi.webp' },
];

export const bonus = [
  { name: 'Controle da despensa', img: 'bonus-despensa.webp', icon: 'organize', home: 'Anote o que preparou e acompanhe seus potes.', income: 'Organize o que produziu e acompanhe seus potes.' },
  { name: 'Ficha da minha conserva', img: 'bonus-ficha.webp', icon: 'note', home: 'Registre ingredientes, data e observações de cada preparo.', income: 'Registre cada preparo para acompanhar o que você fez e repetir com consistência.' },
  { name: 'Botulismo em conservas', img: 'bonus-botulismo.webp', icon: 'shield', home: 'Entenda os cuidados essenciais em uma explicação simples.', income: 'Conheça cuidados fundamentais de segurança alimentar antes de qualquer projeto de venda.' },
];

export const angles = {
  casa: {
    eyebrow: 'O SABOR DA SUA COZINHA, DO SEU JEITO',
    titleBefore: 'Aprenda a fazer',
    titleAccent: 'conservas artesanais',
    titleAfter: 'em casa.',
    description: 'Um guia ilustrado com 15 receitas, ingredientes medidos e passo a passo para você sair das receitas espalhadas pela internet e começar com organização.',
    heroNote: 'Para quem quer preparar, experimentar e aproveitar cada pote.',
    cta: 'Quero preparar minhas conservas',
    problemEyebrow: 'PARECE SIMPLES, MAS…',
    problemTitle: 'Você já salvou uma receita e, na hora de fazer, ficou sem saber por onde começar?',
    problemText: 'Uma informação está no vídeo, outra no comentário e a dúvida sobre o pote ou o tempo aparece bem na hora do preparo. O Método Conserva Fácil reúne o caminho em um só lugar.',
    pains: [
      ['Receitas espalhadas', 'Chega de procurar o próximo passo em vários vídeos.'],
      ['Medo de errar as medidas', 'Tenha ingredientes, rendimentos e orientações organizados.'],
      ['Dúvidas sobre conservação', 'Consulte os cuidados e o processamento indicados para cada receita.'],
    ],
    methodTitle: 'Da vontade de fazer ao seu primeiro pote, com um caminho claro.',
    steps: [
      ['Escolha uma receita', 'Veja as opções doces e salgadas e comece pelo nível que preferir.'],
      ['Siga o preparo completo', 'Confira ingredientes, tamanho do pote e tempo de processamento por altitude.'],
      ['Registre e organize', 'Use os bônus para acompanhar os preparos e cuidar da despensa.'],
    ],
    insideTitle: 'Tudo o que você precisa para consultar durante o preparo.',
    insideText: 'Não é um PDF de receitas soltas: você encontra o que usar, como preparar e o que observar em cada receita.',
    offerTitle: 'Seu próximo preparo começa aqui.',
    offerText: 'O guia digital com 15 receitas e três materiais de apoio por um único valor.',
    faq: [
      ['Sou iniciante. Vou conseguir acompanhar?', 'O guia organiza receitas por dificuldade e explica cada preparo passo a passo. Leia primeiro a seção de segurança e siga integralmente a receita escolhida.'],
      ['As receitas são para um pote só?', 'Não. Cada receita informa seu rendimento aproximado; algumas preparam vários potes. Consulte a quantidade antes de comprar os ingredientes. Não reduza as fórmulas sem uma versão tecnicamente validada.'],
      ['Preciso comprar potes específicos?', 'Sim. O guia indica potes de vidro próprios para conservas, tamanhos recomendados e tampas apropriadas para processamento. Confira os materiais de cada receita antes de começar.'],
    ],
  },
  renda: {
    eyebrow: 'UMA HABILIDADE ARTESANAL PARA APRENDER E EXPLORAR',
    titleBefore: 'Aprenda receitas de conservas que podem virar',
    titleAccent: 'futuros produtos para vender.',
    titleAfter: '',
    description: 'Comece pela base: 15 receitas com quantidades, modo de preparo, tamanho do pote e orientações de processamento. Experimente e registre seus preparos antes de pensar em comercializar.',
    heroNote: 'Primeiro aprenda a receita. Depois avalie a possibilidade de produzir para venda.',
    cta: 'Quero conhecer as receitas',
    problemEyebrow: 'ANTES DE PENSAR NA VENDA',
    problemTitle: 'Uma boa ideia de produto começa com uma receita que você consegue seguir e registrar.',
    problemText: 'Não adianta pensar em embalagem ou divulgação sem conhecer o preparo. Este guia reúne receitas, medidas e orientações para você aprender a técnica e avaliar suas possibilidades.',
    pains: [
      ['Receitas sem padronização', 'Consulte quantidades e procedimentos reunidos no mesmo lugar.'],
      ['Dúvidas sobre o processo', 'Entenda tamanho dos potes, processamento e cuidados básicos.'],
      ['Falta de organização', 'Registre ingredientes, datas e observações a cada preparo.'],
    ],
    methodTitle: 'Aprenda o preparo antes de transformar a ideia em produto.',
    steps: [
      ['Conheça as receitas', 'Explore opções salgadas e doces, organizadas por dificuldade.'],
      ['Pratique seguindo as medidas', 'Siga a formulação e o processamento indicados, sem improvisar proporções críticas.'],
      ['Registre o resultado', 'Use a ficha de conserva para acompanhar seus testes culinários.'],
    ],
    insideTitle: 'Receitas organizadas para tirar sua ideia do improviso.',
    insideText: 'Um material de receitas e preparo: não é um curso de empreendedorismo, precificação, legislação ou autorização sanitária.',
    offerTitle: 'Comece aprendendo as receitas.',
    offerText: 'Um ponto de partida culinário para quem deseja explorar a produção artesanal no futuro.',
    faq: [
      ['O guia ensina a vender e conseguir clientes?', 'Não. Ele ensina receitas, organização do preparo e cuidados de conservação. Não inclui formação de preço, plano de negócios, divulgação ou captação de clientes.'],
      ['Posso começar a vender assim que terminar?', 'O guia não é autorização para comercializar alimentos. Antes de vender, verifique as exigências sanitárias, de produção e rotulagem que se aplicam ao seu município, estado e atividade.'],
      ['As receitas já têm rendimento e tamanho de pote?', 'Sim. As receitas indicam rendimento aproximado e pote recomendado. Os rendimentos podem ser de vários potes e as proporções críticas não devem ser alteradas livremente.'],
    ],
  },
};
